### ISSUE TITLE
No mention that the firmware upgrade is behind a donation.

### ISSUE THREAD

**Issue by raketti** [smokku/pebble#101]
I just got my Time Steel and noticed that the firmware upgrade is actually not free. There's no mention in about, in features or other documentation that you simply cannot upgrade if you do not pay.

Opening the PayPal donation link gives a default amount of 0,00€, so if I donate, say 0,10€ am I entitled to get the upgrade activation code? Or is there a minimum amount preferred/wanted to be donated?

This should be documented, at least I was stunned to get stopped by a pay wall in SailfisOS.

Personal note: I don't mind paying and supporting the app, because I use it pretty much on a daily basis and I think it's really good (could be better, but as an unofficial app, it's good), but the fact that there's no mention about a needed donation is a bit puzzling.

**Comment by nikhau** [comment]
Take a look at this https://github.com/smokku/pebble/issues/54

**Comment by raketti** [comment]
But that doesn't clarify anything, see this answer:
http://talk.maemo.org/showpost.php?p=1491666&postcount=490

It doesn't say anything that a donation is mandatory.

**Comment by nikhau** [comment]
I did a FW update on my Pebble, but it was quite a while ago so I don't remember how things appeared  in the app. However, I do know that I never donated anything.

**Comment by smokku** [comment]
Not completely true.
Te firmware upgrade interface in pebbled is available always. So you are free to do the upgrade ie. via command-line client. In the TMO thread you mentioned I explained how to do this.

**Comment by raketti** [comment]
Ah, ok, didn't see the command line option. But, no matter, I got the code to upgrade and everything is working fine. And you got a few euros for a beer, so win-win (if you drink beer, that is). :)
