### ISSUE TITLE
Pebble 2, Pebble Time Round and Pebble Time 2

### ISSUE THREAD

**Issue by rubdos** [smokku/pebble#109]
Hi!

Anyone planning to add support for the new devices? I am seriously considering ordering a 2 and a Time 2, but I don't really want to implement support on my own. I will help though, if someone else can join in? I would use the Time 2, and would be exclusively with SFOS.

Ruben

**Comment by smurfy** [comment]
Hi,

you could try https://openrepos.net/content/abranson/rockpool
This works with Pebble Time and Pebble Time Round. Not sure about Time 2 but i think the protocol did not change that much.

**Comment by abranson** [comment]
All the Pebble 2 watches are Bluetooth LE only, and Sailfish doesn't support that yet. I expect they'll work in Rockpool if/when it does.

**Comment by rubdos** [comment]
Oh, wasn't aware of that Bluetooth LE fact. That's only a software limitation, right? I'll check with rockpool.

**Comment by smurfy** [comment]
It's a high level software abstraction issue. I have successfully received data from iBeacons via ble advertising. (on my jolla phone)

I don't really remember but i think it had something with the used BlueZ version or something.
