### ISSUE TITLE
Add search function to Pebble store

### ISSUE THREAD

**Issue by HtheB** [smokku/pebble#30]
Adding a search function to Pebble store would be great.
Right now, it's a pain to find the right watchapp/watchface

**Comment by smurfy** [comment]
Yea, that is planned. I just wanted a first iteration to be out.

**Comment by smurfy** [comment]
Also stuff i want to have a look at:
* Scrolling sometimes get stuck
* Add a loading indicator for the browser
* Add backward button for browser
....
Also i will have a look at the android app to see what they have. (I implemented the store without a look at the offical store integration. Just from memory :) )

**Comment by smokku** [comment]
Fixed with 1.1 release.
