### ISSUE TITLE
Call notification does not show contact name

### ISSUE THREAD

**Issue by nikhau** [smokku/pebble#36]
The call notification does show the phone number, but not the contact name. 
The contact name is however shown in sms notifications.

Pebble firmware version: 2.8.1
Sailfish Pebble version: 0.15
Sailfish version: 1.1.1.27 (Vaarainjärvi)

**Comment by smokku** [comment]
What contact details have you available on your phone?

**Comment by nikhau** [comment]
For this particular contact:

Name
Work phone number
Landline phone number
Mobile phone number
A number of e-mail addresses (both private and work)

I just started to use Pebble today so I haven't been able verify how many of my contacts are affected.

**Comment by smokku** [comment]
What is the number showing on call (is it prefixed with + or country code)?
What contact numbers have you entered? Are they prefixed?
Are there any duplicate phone numbers? Current code checks whether ```found.size() == 1```. Maybe we should change it to ```>= 1```.

**Comment by nikhau** [comment]
No duplicates.

All numbers are stored with prefixed with +. The number displayed on Pebble is "local".
Example: stored as +46123456, and displayed as 0123456.

**Comment by smokku** [comment]
https://lists.sailfishos.org/pipermail/devel/2015-March/005911.html

**Comment by smokku** [comment]
@nikhau Does the problematic contact come from som external sync source? (Like Google?)

https://lists.sailfishos.org/pipermail/devel/2014-January/003042.html

**Comment by nikhau** [comment]
@smokku yes the problematic contact is synced from Google account, but so is every contact on my phone, also those that are working.

**Comment by nikhau** [comment]
So yesterday I noticed that the problematic contact name is properly shown on my Pebble. I have not touched my contacts what so ever. However, I have promptly updated firmware, Sailfish and apps at releases.
Was the proposed check above introduced into the code and released, or have Jolla made something to the handling of contacts, or what did happen?

Now working with current setup:
Pebble firmware version: 2.9.1
Sailfish Pebble version: 1.0
Sailfish OS version: 1.1.4.29

**Comment by smokku** [comment]
There was no changes in contact directory handling.

**Comment by nikhau** [comment]
After some reading on Together, I might have found something interesting, so this is speculation, and thus could be a plausible theory or just pure mumbo jumbo.

All my contacts are synced from Gmail, and Jolla has serious problems handling contacts syncing with Gmail. https://together.jolla.com/question/45961/two-way-syncronization-of-google-contacts-not-working-properly/

Problems with the syncing even seems to affect contact handling over Bluetooth PBAP profile. https://together.jolla.com/question/45859/after-update-carkit-bluetooth-not-working/#post-id-46914

However, some improvements were released with 1.1.4, and more seems to be in pipeline. https://together.jolla.com/question/45961/two-way-syncronization-of-google-contacts-not-working-properly/?comment=92215#comment-92215

So, this might be the explanation to why my problematic contact suddenly started to work after I upgraded my Jolla to 1.1.4. But maybe I have to engage Mythbusters to verify or dismiss this theory ... ;)

**Comment by smurfy** [comment]
I can confirm there is something strange with contacts.

For example i have one contact where a nickname is displayed. I know the nickname but if i look at the Contacts this particular nickname is not listed anywhere. If i get a call i see the no-where to be found nickname on pebble and the real-name on my phone.

My guess is the nick is coming somewhere from an im contact (gmail or jabber).

The Problem i describe is also in WhatsUp 's contact list, so its related somehow with how apps can fetch the contacts from the contacts framework and the displayName.

Not sure what you are getting instead of the contact name but based on your description you get "blank" which could be the same problem with my wrong nick. (it somehow uses a not filled nickname of a linked account)

I wanted to take a look at the code to figure out which names comes. but i had no time yet.

**Comment by nikhau** [comment]
"Not sure what you are getting instead of the contact name but based on your description you get nothing and a blank space,"

I only got the phone number, just like what I get with a call from somebody not in my contact list.

**Comment by abranson** [comment]
Have you checked if those contacts you're having problems with differ between the main contacts.db at /home/nemo/.local/share/system/privileged/Contacts/qtcontacts-sqlite/ and the lower security one at /home/nemo/.local/share/system/Contacts/qtcontacts-sqlite/. I heard there was some screwy differences between those.

**Comment by nikhau** [comment]
It works for me, since my post in end of April. Nobody else has reported this issue, so it seems 'solved'. I will close it, but please re-open if issue re-appear.
