### ISSUE TITLE
Morpheuz App not working

### ISSUE THREAD

**Issue by awlx** [smokku/pebble#37]
Yesterday I wanted to try Morpheuz on my Pebble but there are two problems. First it isn't able to be installed via pebbled. And second after installing it via an Android device. The settings cannot be shown on the Jolla. But I think it's a JS Pebble app according to the author.
Infos:
http://forums.getpebble.com/discussion/8616/watch-app-morpheuz-sleep-monitor-with-smart-alarm-healthkit

Download:
http://www.mypebblefaces.com/apps/9400/7424/

**Comment by smurfy** [comment]
Yes, some apps have problems installing, see #34, also if you don't install the app via pebbled the settings are not available. (because the companion part is not installed on the phone)

**Comment by awlx** [comment]
But the Morpheuz App shows up in the available Apps for install screen. If I select a new empty slot. Shouldn't be everything in place? Or should I do a manual extraction and test again?

**Comment by smurfy** [comment]
The "available apps" screen lists the archives. 
You would need to extract the file to the correct folder.

**Comment by awlx** [comment]
Ok, I extracted it. Afterwards it hangs a bit and shows "No configuration settings available"

Logs are:
Feb 06 13:42:00 Jolla [31183]: [D] configure:110 - going to call configure on app with uuid {5be44f1d-d262-4ea6-aa30-ddbec1e3cab2}
Feb 06 13:42:00 Jolla [31183]: [D] PebbledInterface::configureApp:191 - QUrl PebbledInterface::configureApp(const QString&) "{5b...3cab2}" 
Feb 06 13:42:00 Jolla pebbled[17247]: [D] JSKitManager::showConfiguration:43 - requesting configuration 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] WatchConnector::onReadSocket:189 - readyRead bytesAvailable = 6 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] WatchConnector::onReadSocket:229 - received message of length 2 to endpoint "watchDATA_LOGGING" 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] DataLogManager::DataLogManager(WatchConnector*, QObject*)::<lambda:24 - timeout datalo...ion 157 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] WatchConnector::onReadSocket:189 - readyRead bytesAvailable = 6 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] WatchConnector::onReadSocket:229 - received message of length 2 to endpoint "watchDATA_LOGGING" 
Feb 06 13:42:01 Jolla pebbled[17247]: [D] DataLogManager::DataLogManager(WatchConnector*, QObject*)::<lambda:24 - timeout datalo...ion 171

**Comment by smurfy** [comment]
No time to check myself, but does the watchapp has a configuration screen on android?.
Also i think after extracting the js part it could be possible that at least the companion part is now running on the phone.

**Comment by awlx** [comment]
It displays this page on Android:
https://raw.github.com/JamesFowler42/morpheuz20/master/config-screen.png

**Comment by smurfy** [comment]
Looks like a config screen :D

The thing is, i don't know why installing of some apps does work and some don't.
If you look at the debug messages of pebbled it at least trys to upload :)
I did not implement the upload stuff but it looks quite straight forward. I was thinking maybe its app size, but i did not check that.

**Comment by awlx** [comment]
Well, the installing is no problem for me as long as it works via Android ;). But the missing configuration option is a problem with some Apps. I have a look at it if I can find anymore debug output.

**Comment by smokku** [comment]
There's no need to extract it anymore. Having an app on "Available Apps" is sufficient.

**Comment by smokku** [comment]
Fixed with #47
