### ISSUE TITLE
GPS read

### ISSUE THREAD

**Issue by storma** [smokku/pebble#38]
I have two apps that require a GPS location and neither work.
1. Get back. It reads in an initial GPS location and allows you to track back to it.
2. PTV. This is a transport timetable app. Reads in a location and fetches local timetables around where you are. Though this one also needs data access.

**Comment by nikhau** [comment]
I might be out on deep water, but I think that this may be related to availability of positioning data: https://together.jolla.com/question/80045/time-to-allow-qtpositioning-module-in-the-store/

**Comment by smurfy** [comment]
@nikhau thanks for your input, this is not relevant.
- pebbled is not available in the store, only openrepros so not restricted by harbour rules
- i for one also have an other app in the store WITH gps support so i guess jolla does not really enforce the rules :)

About the problem itself, i did not test the apps yet, if they are pebble js kit based the gps stuff should work. Otherwise i guess the app needs a companion on the phone.
I will check the apps if i have time.

**Comment by nikhau** [comment]
@smurfy, I know pebbled is in openrepose and therefore not restricted. But as both QtPositioning and QtLocation are (or were) very shaky, this could be a reason for not implementing it pebbled. That's why I suggested the issue.
However, things seems to have stabilized, and there are a lot of pebble watch faces and apps that use positioning and weather data. So, it would be nice if pebbled could incorparate such data handling (in a suitable manner).

**Comment by smurfy** [comment]
I will have a look, i use a watch face with gps support which returned wrong weather data if i configured the use of gps position, 

so it's possible that there is a problem with the implementation.

**Comment by storma** [comment]
It does use js. I'll have another look at it.
https://github.com/samuelmr/pebble-getback

**Comment by javispedro** [comment]
Getback definitely works, I often use it...

**Comment by smurfy** [comment]
@storma how did you install the watch apps / faces? 
Using pebbled or via android? 

The thing is if you have installed it via android, the companion pebble js kit part is missing on pebbled.

**Comment by nikhau** [comment]
@smurfy, thanks for the clarification! I now got another WatchFace to work properly via Jolla by installing the WatchFace via pebbled.

**Comment by smokku** [comment]
I guess I need to add big red "Companion app missing!" caption on app list screen in this case.

**Comment by storma** [comment]
Yes, I had installed it via android. Thanks for the clarification.

**Comment by smokku** [comment]
Latest release informs about too old firmware and missing companion apps.

**Comment by PeterSumm** [comment]
Hi, Storma.  Did you ever resolve this?  I've had the same problem and have done a lot of work trying to resolve it.

Thanks,

Peter

**Comment by storma** [comment]
G'day PeterSumm. Yes I did. By installing everything through pebbled, they work as expected.

**Comment by PeterSumm** [comment]
That's weird.  

I've just confirmed today that a friend's iPhone 6 and Pebble combination has the same issue as mine.

I spent a lot of time rewriting Get Back to work properly on the iPhone and eventually got to something that I've put on the app store as Get Back To, but there's a fair bit of tricky javascript behind it.  Likewise, I have a watchface that finally does locations properly if you set it appropriately (Moon, Location and Weather Watch), but it took hours of programming on a laptop and watching app logs while travelling on public transport before I was happy with it.

I started a conversation with Alex of Pebble support about it, but haven't heard back from him for a while.

Thanks for your input

**Comment by PeterSumm** [comment]
Speaking of which, does anyone know a good way to detect the phone type in javascript?  The navigator object properties don't seem to work as I'd expect.

**Comment by smokku** [comment]
Please do not mix issues. This one is about GPS.
Please create separate issue describing the problem and pointing to relevant specification of missing feature.

**Comment by PeterSumm** [comment]
Er, OK.  It appears there's a bug in the iPhone's handing of the GPS.  Can anyone suggest a way of detecting that this needs to be worked around?

**Comment by PeterSumm** [comment]
Actually, I suspect this is pretty straightforward:

1) Read the GPS with the maximum age set to zero and note its timestamp.
2) Wait a few seconds.
3) Read the GPS again with the maximum age set to zero and note its timestamp.
4) Compare the two timestamps - if they're the same, you've got the problem.
