### ISSUE TITLE
Cannot connect to Pebble

### ISSUE THREAD

**Issue by TheRealCodeboss** [smokku/pebble#41]
I have two Pebble watches laying around, a Steel ID 4xxx and a plastic one with ID 6xxx. My Jolla is only paired with the 4xxx, but Pebbled's homescreen widget always says "Pebble 6xxx disconnected".

Even if the 6xxx Pebble is shutdown and I rebooted the phone, Pebbled somehow tries to find the 6xxx. Re-paring or reinstalling Pebbled also does not solve this problem. Only occasionally Pebbled connects to the paired 4xxx. If so, it seems to last until next reboot and then the lottery is back on.

The 6xxx was never paired to this phone.

**Comment by smokku** [comment]
I guess we will have to wait until May - when I get my Pebble Time I will try to reproduce and debug this. ;-)
