### ISSUE TITLE
cant install apps

### ISSUE THREAD

**Issue by scribepl** [smokku/pebble#44]
im have downloaded aps, put them into directory, then open slot and install. circles are roling into infiniti, but aps dont mov to pebble. any idea why?

**Comment by krafel** [comment]
into which directory did you put them? I also try to install apps but don't even see therespective screens or the appstore! i am running version 0.15-1...

**Comment by smurfy** [comment]
see #34 

it's a known problem.

**Comment by scribepl** [comment]
firmware was old, problem resolved when im updated (on android device) my pebble. Now everything works gr8!

good aplication!
