### ISSUE TITLE
Automatic time synchronization is missing

### ISSUE THREAD

**Issue by eras** [smokku/pebble#46]
Related to #10.

There is no automatic time synchronization. It'd be nice to have the watch always be on _exact_ time (ie. less than 0.2s difference from the phone); I usually don't remember to do it (ever) and then wonder why the watch is off by the minute digit ;).

Once a day sync sounds OK to me if hourly sync eats too much battery. Preferably it would take DST transitions and time zone changes into account. So the logic could be: if localtime differs from the previous poll a different amount than the polling interval would suggest, or if there's been long enough since last resync, do the resync.

**Comment by smurfy** [comment]
I think the official app does a sync on connect.
While implementing the time sync i choose to do a manual sync. 
But sure we could scrape that and do an automatic one.

**Comment by smokku** [comment]
My vote:

    on connect:
      if last_sync < 4h then sync()

**Comment by eras** [comment]
Though, how about next Sunday, when we switch to summer time in Europe? Do I need to manually click 'sync time' like a peasant or will Pebble know the time zone for me?-) In particular this would affect alarm times, if one uses the Pebble-based alarm at the morning.

**Comment by smokku** [comment]
Yup... You will have to switch time like a peasant...

**Comment by abranson** [comment]
This would be more efficient if the daemon could be told by the OS when the system time is adjusted. Is that possible?

**Comment by smokku** [comment]
The point is the watch time drift, not the system time drift.

**Comment by smokku** [comment]
Oh. You mean the daylight-saving change...

**Comment by abranson** [comment]
And roaming/crossing timezones.
