### ISSUE TITLE
Volume controls in pebble music app don't work

### ISSUE THREAD

**Issue by abranson** [smokku/pebble#48]
When using the stock Sailfish music player, the volume controls on the pebble have no effect. The play/pause and skip controls work.

**Comment by smokku** [comment]
This is because stock music player does not have volume control.

**Comment by smurfy** [comment]
why not change the system volume?

**Comment by smokku** [comment]
Because it is _system_ volume and affects not only music.

**Comment by smokku** [comment]
To be clear - volume control via MPRIS2 is already implemented. It is up to the current MPRIS2 interface owner (usually music player) to react somehow when it gets vol-up/vol-down request.

**Comment by abranson** [comment]
So your expected resolution to this would be that Jolla implement volume control in their media player, probably by passing it on to the system volume? Are there any media players you know of that do this already? I have Daedalus installed, but although that seems to have MPRIS implemented, it doesn't work with the pebble at all.

**Comment by nikhau** [comment]
@abranson , you might wanna read this
https://together.jolla.com/question/75875/control-audio-volume-from-external-sources-headphones-bluetooth-speakers-pebble-headsets-carkits/

You are pretty much spot on regarding how to solve the issue.

**Comment by abranson** [comment]
Thanks, that's very interesting, though seems to be more concerned with external devices such as carkits which do not have their own daemons running on the phone. Apparently it is currently possible to control the system volume via DBus, but only through the org.PulseAudio.Core1.Device interface, which would be a pragmatic alternative, not to mention extremely useful. 

https://github.com/jusa/pulseaudio-utils/blob/master/mainvolume-volume.py

After all, the current code may be cleaner, but the current situation justifies a workaround which wouldn't be particularly messy.
Maybe a config option in the pebble app to 'Control system volume' that switches between the DBus calls might be less filthy?

**Comment by smokku** [comment]
I am reluctant to implementing global volume changing by controls clearly dedicated to music. I imagine someone being very surprised/annoyed on a missed phone call because of low ringer volume, just because one turned the music quiet.

**Comment by abranson** [comment]
I just tested the music app on my android tablet, and the volume buttons alter the system volume on there. I tested MX Player and Google Play Music. There was also a progress bar under the track name showing the track position.

The system volume is independent of the ringtone volume.
