### ISSUE TITLE
Configuration pages of apps don't work in pre release or 1.1.4.28 Äijänpäivänjärvi

### ISSUE THREAD

**Issue by awlx** [smokku/pebble#49]
Hi,

the configuration pages don't work anymore. Get the following errors in journalctl:
>Apr 17 10:22:51 Jolla [8477]: [W] PebbledInterface::configureApp:224 - Received error: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply ti...nection was broken." 
>Apr 17 10:22:51 Jolla [8477]: [D] configure:106 - received url: 
>Apr 17 10:22:51 Jolla [8477]: [W] WebKitQmlExperimentalExtensionPlugin::registerTypes:52 - 
                              WARNING: This project is using the experimental QML API extensions for QtWebKit and is therefore tied to a specific QtWebKit release.
                              WARNING: The experimental API will change from version to version, or even be removed. You have been warned!...
>Apr 17 10:22:52 Jolla [8477]: [W] QQmlJavaScriptExpression::evaluate:184 - QQmlExpression: Expression file:///usr/lib/qt5/qml/Sailfish/Silica/SilicaWebView.qml:128:16 depends on non-NOTIFYable properties:
>Apr 17 10:22:52 Jolla [8477]: [W] QQmlJavaScriptExpression::evaluate:184 -     QQuickWebViewExperimental::transparentBackground

Note this is SailfishOS version: 1.1.4.28 Äijänpäivänjärvi

Cheers

**Comment by raketti** [comment]
I'm using 1.1.4.28 and for all the installed wathc faces and apps the confuguration pages load as they should. The only one which doesn't load is Battery lifetime (black). I used the pre-release of pebble for a while and noticed this issue, and reverted back to the OpenRepo -version, now everything works correctly.

**Comment by awlx** [comment]
Ok, so it's a issue of the pre release and not the Jolla release.

**Comment by raketti** [comment]
I would strongly suggest so.
