### ISSUE TITLE
version 0.16-1: "Your firmware is too old.." though Settings/About/Firmware says v2.9

### ISSUE THREAD

**Issue by eras** [smokku/pebble#51]
The application view says "Your firmware is too old to support SDKv2 applications" though when I check the firmware on the Pebble itself under Settings/About/Firmware there is v2.9 which I understand is the most recent firmware available.

If I press Info on pebbled it just says "Address Serial Number BootLoader Firmware Recovery" and no additional information, but perhaps this part isn't implemented yet.

My Sailfish version is 1.1.2.16.

**Comment by eras** [comment]
I noticed that I still had the old Pebble background process running. I disabled/enabled everything on the main page and now that particular message is gone. Also Info now works.

So perhaps this bug would better be about that not happening automatically on upgrade? Or another issue about it?

**Comment by smokku** [comment]
It's a known issue, which has been fixed in 01dca8bb
