### ISSUE TITLE
Unable to connect to Pebble

### ISSUE THREAD

**Issue by reinouts** [smokku/pebble#52]
Pebble firmware: 2.9.1
Sailfish OS: 1.1.2.16

My Pebble and Jolla phone are properly paired and Bluetooth is enabled on both devices.
However, Pebble Manager is unable to connect to the watch. 
When I press 'Active', the screen flashes a few times with a message 'Waiting for watch..' and then immediately returns to the initial screen in 'Dead' state. Pressing 'Connection' has no effect.

What can I do to (help you to) debug this?

**Comment by smokku** [comment]
Please provide:

    systemctl --user status pebbled.service

**Comment by reinouts** [comment]
It's hard to copy and paste from the Jolla terminal, but I'll type over
some relevant lines:

Active: failed (result: start-limit) since Mon 2015-04-20 14:12:06 CEST; 9h
ago
Process: 29389 ExecStart=/usr/bin/pebbled (code=exited, status=127)

/usr/bin/pebbled gives:

Symbol lookup error: /usr/bin/pebbled: undefined symbol:
_ZN11QtBluetoothSocket16staticMetaObjectE

Thanks!
Op 20 apr. 2015 16:27 schreef "Tomasz Sterna" <notifications@github.com>:

**Comment by smokku** [comment]
This really looks like your system is broken. QtBluetooth should be pulled-in by package dependency.

**Comment by reinouts** [comment]
I simply installed via Warehouse - everything else works fine. Can I
install the missing package manually via the terminal?

2015-04-21 16:12 GMT+02:00 Tomasz Sterna <notifications@github.com>:

> This really looks like your system is broken. QtBluetooth should be
> pulled-in by package dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-94810169>.
>



-- 
Reinout van Schouwen

**Comment by reinouts** [comment]
Further info: 'pkcon search qtbluetooth' confirms that
qt5-connectivity-qtbluetooth-5.2.0+git0-1.4.6.armv7h1 is installed.
Debuginfo and devel files are not, but also not required I presume.

2015-04-21 21:28 GMT+02:00 Reinout van Schouwen <reinout@gmail.com>:

> I simply installed via Warehouse - everything else works fine. Can I
> install the missing package manually via the terminal?
>
> 2015-04-21 16:12 GMT+02:00 Tomasz Sterna <notifications@github.com>:
>
>> This really looks like your system is broken. QtBluetooth should be
>> pulled-in by package dependency.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smokku/pebble/issues/52#issuecomment-94810169>.
>>
>
>
>
> --
> Reinout van Schouwen
>



-- 
Reinout van Schouwen

**Comment by reinouts** [comment]
I have shown that QtBluetooth is actually installed, so my system isn't broken (at least not in that respect). What else can I do to resolve this problem?

**Comment by abranson** [comment]
Are the files there? You should have the following in /usr/lib/:

libQt5Bluetooth.so.5  libQt5Bluetooth.so.5.2  libQt5Bluetooth.so.5.2.2

The first two are symlinks to the third.

**Comment by reinouts** [comment]
Confirmed, they are there. libQtBluetooth.so.5.2.2 has a size of 327464
bytes.


2015-04-28 23:31 GMT+02:00 Andrew Branson <notifications@github.com>:

> Are the files there? You should have the following in /usr/lib/:
>
> libQt5Bluetooth.so.5 libQt5Bluetooth.so.5.2 libQt5Bluetooth.so.5.2.2
>
> The first two are symlinks to the third.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-97217053>.
>



-- 
Reinout van Schouwen

**Comment by abranson** [comment]
Mine is:

-rwxr-xr-x 1 root root 324332 Apr  8 22:31 libQt5Bluetooth.so.5.2.2

I don't know what the significance of that difference is. I just updated to the 1.1.4.29 jolla update this evening.

**Comment by reinouts** [comment]
I'm still on 1.1.2.16 waiting for the GA of the update. My
libQtBluetooth.so.5.2.2 is dated Feb 6th.
Is it possible I have a wrong version? How would I reinstall it without
breaking stuff?

2015-04-28 23:53 GMT+02:00 Andrew Branson <notifications@github.com>:

> Mine is:
>
> -rwxr-xr-x 1 root root 324332 Apr 8 22:31 libQt5Bluetooth.so.5.2.2
>
> I don't know what the significance of that difference is. I just updated
> to the 1.1.4.29 jolla update this evening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-97236620>.
>



-- 
Reinout van Schouwen

**Comment by abranson** [comment]
Looks to me that it should be the same. Pkcon tells me I have the same version installed as you do: qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.4.6.armv7hl. That package isn't on the release notes for 1.1.4, Zypper will reinstall:

zypper in -f qt5-qtconnectivity-qtbluetooth

That's probably a bit dangerous without knowing why your version is wrong though. Do you have any other warehouse apps installed that may have bundled the bluetooth? People were getting similar errors to you last year when the SDK was updated, so if someone bundled an older BT version as a workaround at that time, you could get in this mess.

**Comment by reinouts** [comment]
I first had to install zypper, but once that was done I did what you suggested. qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.4.6.armv7h1 was reinstalled. However I keep getting the same error when running pebbled. :(

**Comment by abranson** [comment]
Did the libQtBluetooth.so.5.2.2 file get changed?

**Comment by reinouts** [comment]
327464 bytes, dated Feb 6 15:27. I even tried disabling all openrepos
repositories except smokku before reinstalling qtbluetooth, but it made no
difference.

2015-04-29 17:16 GMT+02:00 Andrew Branson <notifications@github.com>:

> Did the libQtBluetooth.so.5.2.2 file get changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-97463279>.
>



-- 
Reinout van Schouwen

**Comment by abranson** [comment]
Try:

pkcon search file /usr/lib/libQt5Bluetooth.so.5.2.2

to see if there are any other packages holding that file. I get:

pkcon search file /usr/lib/libQt5Bluetooth.so.5.2.2
Searching by file
Waiting in queue
Starting
Refreshing software list
Querying
Installed       qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.4.6.armv7hl QtBluetooth

**Comment by reinouts** [comment]
Executed that, and I have the exact same output as you do.

2015-04-30 11:56 GMT+02:00 Andrew Branson <notifications@github.com>:

> Try:
>
> pkcon search file /usr/lib/libQt5Bluetooth.so.5.2.2
>
> to see if there are any other packages holding that file. I get:
>
> pkcon search file /usr/lib/libQt5Bluetooth.so.5.2.2
> Searching by file
> Waiting in queue
> Starting
> Refreshing software list
> Querying
> Installed qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.4.6.armv7hl
> QtBluetooth
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-97725468>.
>



-- 
Reinout van Schouwen

**Comment by awlx** [comment]
Maybe you should compare the md5sum of the file?
201c1142d8d26fd0945babdadb6cdc5b  /usr/lib/libQt5Bluetooth.so.5.2.2

**Comment by reinouts** [comment]
The date and size already indicates the file is different, md5sum confirms
that: my md5sum starts with 723b.


2015-04-30 14:46 GMT+02:00 awlx <notifications@github.com>:

> Maybe you should compare the md5sum of the file?
> 201c1142d8d26fd0945babdadb6cdc5b /usr/lib/libQt5Bluetooth.so.5.2.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smokku/pebble/issues/52#issuecomment-97759793>.
>



-- 
Reinout van Schouwen

**Comment by abranson** [comment]
201c1142d8d26fd0945babdadb6cdc5b  /usr/lib/libQt5Bluetooth.so.5.2.2 here too, so we've confirmed that his file is the wrong one. His package version is right, so what's going on?
@reinouts, which repos did you have enabled? Maybe the pkcon file search won't have picked up the alternate package if the repo containing it is disabled. Maybe reenable them, do an update check in warehouse to load them all, then run my search again.

**Comment by reinouts** [comment]
@abranson The other repos are: openrepos-veskuh, openrepos-netvandal, openrepos-ellefj, openrepos-localhost, openrepos-basil, openrepos-Schturman, and openrepos-HtheB. After disabling them all, deinstalling QtBluetooth and pebble, and then reinstalling, apparently the right version is pulled in because pebbled actually starts up! It still doesn't connect to my Pebble though, it's just "waiting for watch" indefinitely. But this specific issue is solved now.
