### ISSUE TITLE
"Update firmware" option is underdocumented

### ISSUE THREAD

**Issue by tadzik** [smokku/pebble#54]
The changelog for 1.0 says it's now possible to update firmware, but there does not seem to be any way to do it from the app. A thread on talk.maemo.org seems to indicate that the feature is hidden behind a paywall; can you clarify?

**Comment by smokku** [comment]
This feature is visible in UI only if the firmware is old. If you have the latest firmware, the button to upgrade is not visible, as there is nothing to upgrade to.

**Comment by tadzik** [comment]
Huh. Well, I eventually upgraded from an android phone, so now I have no means of checking that; I *thought* I looked there... But if that's so, then this probably should be closed.

**Comment by smokku** [comment]
Look at the watch "Info" screen under Firmware section.
Is Latest the same as Running? If so - there is no need to show "Upgrade Firmware" button there.

**Comment by tadzik** [comment]
Yeah, indeed, now it is :) I must have not noticed this option when I was looking how to update my firmware, and since I seem to be the only one with the problem, it's probably just my mistake :) Thanks for clarifying that.
