### ISSUE TITLE
"Logout" in app store is very easy to trigger accidentally

### ISSUE THREAD

**Issue by tadzik** [smokku/pebble#55]
When swiping up on the appstore it's easy to accidentally trigger the Logout pulley option, which then immediately logs me out and forces to re-login, which is annoying as @#%$. Perhaps a remorse timer could be of use here?

It's especially problematic because of how fragile the scrolling in app store is, and the only reliable way to actually scroll up instead of triggering a pulley menu is to scroll down a little and then start going up.

**Comment by smokku** [comment]
Remorse timer is a good idea.  This is exactly what it is designed for.

**Comment by nikhau** [comment]
+1 on this one. I really have big difficulties scrolling the app store, and have by accident logged out too many times.

**Comment by awlx** [comment]
Very good idea!

**Comment by raketti** [comment]
I knlw the store is in an early stage, but the scrolling really needs to be improved. It works quite randomly.

**Comment by smurfy** [comment]
I'm started working on that again, will fix the logout the way suggested.

About scrolling a bit buggy, it's a normal webview, i'm not quite sure why it behaves that way.
