### ISSUE TITLE
"Silent when connected" toggle is ignored

### ISSUE THREAD

**Issue by tadzik** [smokku/pebble#59]
I have it turned off all the time, and yet my profile is being set to silent whenever my pebble (re)connects.

**Comment by abranson** [comment]
I think I've found a possible cause of this in Manager.applyProfile(). The daemon records the current profile when it starts, and if 'silent when connected' is set to false, it will set that profile every time the watch connects. If your phone was on silent the last time it started, it will keep setting it to silent.

To test this, if your phone keeps switching to silent, set it to normal then restart the pebble daemon (tap 'Active' once to stop it, then again to start it and see if it still does it.

A possible solution would be to listen for profile changes and update the stored profile name, or really the daemon shouldn't be setting the profile at all if that setting is false.

**Comment by smokku** [comment]
Please test whether https://github.com/smokku/pebble/releases/tag/3f64297 pre-release solves this issue.

**Comment by smokku** [comment]
Assumed 1.1 release fixes it.
If not - feel free to reopen.
