### ISSUE TITLE
Phone calls aren't forwarded sometimes

### ISSUE THREAD

**Issue by tadzik** [smokku/pebble#60]
It happened a few times already, my phone would ring, but no call would be forwarded to the watch. It's especially annoying when combined with #59, since I'd have no indication whatsoever that a call is being made. Seems to happen usually after a pebble disconnects (ie I walked out of range) and reconnects. The pings sent would still get through after that, but phone calls sometimes do not.

**Comment by nikhau** [comment]
Duplicate of https://github.com/smokku/pebble/issues/33 ?

**Comment by tadzik** [comment]
Seems to be the same problem, and #33 is more detailed. Closing this one, thanks.
