### ISSUE TITLE
Firmware upgrade stuck at 0%

### ISSUE THREAD

**Issue by ostkind** [smokku/pebble#61]
Started firmware update from the "pebble" app, after receiving unlock code.

The watch started the update process but is stuck (60 min now) at: "Updating ... 0%". Unresponsible then, only a 10 sec key-press makes the watch restart. Everything is fine after reboot, but firmware version is the same as before update.

The watch is brand-new, runs firmware v1.5.4, bootloader from 17.01.2013. Tried to update to firmware v2.9.1 on a Jolla with 1.1.2.16 (Yliaavanlampi) and "pebble" app v.1.0-1.

**Comment by smokku** [comment]
I've never tried upgrading v1.x firmware to v2.x firmware. I'm not sure whether that works.
Will need to investigate.

**Comment by ostkind** [comment]
Tried a couple of times more right know. Surprisingly update succeeded! After the 10th try process went fast an smoothly, phone rebooted and runs know v2.9.1. Consider this issue maybe closed.

**Comment by smokku** [comment]
#heisenbug :(

**Comment by smokku** [comment]
How far was your watch from the phone? Is your watch-phone connection stable when normally connected?

**Comment by ostkind** [comment]
The watch was 10 centimeters away from the phone. Connection is absolutely stable, even on distances of about 10 meters through concrete walls. The only hickup I could encounter is when the phone switches wifi connections. Not very often watch disconnects during a normal telephone call and reconnects immediately after it.

**Comment by smokku** [comment]
If you have anything to add, feel free to reopen.
