### ISSUE TITLE
Too many notifications with SailfishOS 1.1.6

### ISSUE THREAD

**Issue by 127001** [smokku/pebble#67]
I upgraded to the early release version of SailfishOS 1.1.6 yesterday and since then I can't control which notifications are sent to the phone. They are all sent :-(

I tried to enable and disable certain notifications, but that didn't help (e.g. I have email notifications turned off). Turning off all notifications still sends them to my Pebble.

I checked the changelog for this release and there are many notification changes, but I can imagine the following change related to [notifications](https://together.jolla.com/question/95125/changelog-116aaslakkajarvi/#None-nemo-qml-plugin-notifications-qt5) could be relevant:

> **nemo-qml-plugin-notifications-qt5**
> * [nemo-qml-plugin-notifications] Separate appName from notification ownership
> * [nemo-qml-plugin-notifications] Add property for notification urgency
> * [nemo-qml-plugin-notifications] Add utility function to construct action variant
> * [nemo-qml-plugin-notifications] Prefer application name to filename
> * [nemo-qml-plugin-notifications] Fix broken encoding when no action name is specified

**Comment by smurfy** [comment]
I will try to have a look

**Comment by smokku** [comment]
There are two issues with supporting unreleased SailfishOS versions:
  * I am not kamikaze and use only stable os line
  * there is no SDK release for unreleased SailfishOS

**Comment by awlx** [comment]
Yeah, but unstable SailfishOS is a good thing because you are able to fix problems in your application before the upgrade hits the masses.

**Comment by 127001** [comment]
Guess I'll have to wait until those are released. If I can help sending logs (not that I know how to generate them, please tell).

**Comment by abranson** [comment]
The app_name has changed in the notification to something more readable, and the old value has been moved to a hint called x-nemo-owner. Everything was falling through to the 'other notifications'

**Comment by nikhau** [comment]
So this would maybe explain why I get double notifications (sms and android notifications) in my Pebble, after upgrading to Sailfish 1.1.6. Emails are only notified once, as previously.

Sailfish 1.1.6.27
Pebbled 1.2
Pebble FW 2.91

**Comment by abranson** [comment]
No, this is just a mis-categorization. Will keep an eye out for double messages.

**Comment by nikhau** [comment]
Ok, thanks! Since Pebble basically only display one message at a time, some scrolling is needed to detect it. Or, in your Pebble, go to Notifications, and scroll your history.

**Comment by abranson** [comment]
I think I saw some odd behaviour with IM messages. Is the first one the message content, while the second is just a '2 new messages' general notification?

**Comment by nikhau** [comment]
No, they are duplicates (identical) so each message is displayed twice. In the Notificaion history the two  occurances have their own "list number", e.g. notification numbers 46 and 47, and they are identical. Mainly happens with sms, but also some Android notifications such as Skype.

Maybe should open a separate issue, if this is not related to the mis-categorization?

**Comment by abranson** [comment]
Yep, definitely a different issue.

**Comment by nikhau** [comment]
duplicate notifications are now https://github.com/smokku/pebble/issues/69 so we can put this issue to rest.

**Comment by 127001** [comment]
Not sure of this should be closed. I do not receive duplicate messages and I do receive All kind of notifications even of my settings are set to no notifications at all.

**Comment by abranson** [comment]
I just tested this with Email and Messaging, and the switching on and off worked as intended. I did see #33 last night when I was working on this, but didn't save the log so will have to try to replicate it again.

**Comment by 127001** [comment]
Pulled master and build the rpm. Issue indeed seems to be resolved. Thanks!
