### ISSUE TITLE
Duplicate notifications with SailfishOS 1.1.6

### ISSUE THREAD

**Issue by nikhau** [smokku/pebble#69]
After upgrading to Sailfish 1.1.6.27 I get duplicate notifications on my Pebble.
Sms and Android notifications are displayed twice, and are also occuring as double entries in the Notification history.
Emails seems to show only once.
I don't use Twitter nor Whatsup, so I don't know how these messages are handled.

Sailfish 1.1.6.27
Pebbled 1.2
Pebble FW 2.91

**Comment by raketti** [comment]
Having the same issue with SMS notifications, same versions of App and SFOS as @nikhau. I only use Viver as an Android messaging App and it seems to work correctly. Also haven't noticed anything odd in other notifications - regarding duplicates.

**Comment by ktulu73** [comment]
I've just opened a issue for call notifications with 1.1.6, but whatsup and missed calls are working so far.

**Comment by smokku** [comment]
Is this still valid for release 1.3?

**Comment by nikhau** [comment]
After a first quick test, it seems fixed with 1.3.

**Comment by nikhau** [comment]
Seems to work .. most of the time.

I have received a couple of sms during this morning, all notified once in the watch.
But then all of a sudden I got a double notification again.
I had my phone on my desk and walked out of Bluetooth range.
When returning, I got the double notification. The sms arrived at the phone about the same time as I returned into Bluetooth range.

**Comment by nikhau** [comment]
No reports that double notifcations are received on version 1.3, so this can be closed.

**Comment by smokku** [comment]
thx
