### ISSUE TITLE
MPRIS support

### ISSUE THREAD

**Issue by smokku** [smokku/pebble#8]

**Comment by tadzik** [comment]
It seems to work pretty randomly. I'm using daedalus, which has built-in mpris support, and when I enter the pebble music app (being connected, pingable from the jolla app etc), it often says "No music found". Sometimes restarting pebbled, music player, bluetooth etc in an improvised order makes things work for a while, but I can't even reproduce it reliably.

Any way I can debug this further?

**Comment by smokku** [comment]
Looks like a player issue. After latest Javier changes MPRIS had been stable as rock for me both with the stock player and with Quasar MX.

**Comment by tadzik** [comment]
Indeed, I tried it with Stock now and it works like a charm. I'll open issues in Daedalus then, thanks :)
