### ISSUE TITLE
Notifications do not work with Pebble Time

### ISSUE THREAD

**Issue by HtheB** [smokku/pebble#82]
Notifications do not work with the Pebble Time

**Comment by nikhau** [comment]
I've just received my Pebble Time Steel.

Call notification works.

Sms and email notification do not work.

Pebble FW 3.4
Sailfish 1.1.9.28
Pebbled 1.3-1

**Comment by cgfrost** [comment]
I got my Pebble Time Steel today as well. I can connect the app to the watch but I just get a notice in the app saying `SDKv2 isn't supported.` So not even far enough to update the firmware.

Will hook it up to an Android phone later to get going and see if that helps at all.

Pebble - What ever it shipped with...
Sailfish 1.1.9.28
Pebbled 1.3-1

**Comment by nikhau** [comment]
I got that (SDKv2) as well. Connected my PTS to an Android and updated the firmware, before reconnecting to my Jolla.

**Comment by locusf** [comment]
WHERE IS MY PTS!!!! (lol)

**Comment by cgfrost** [comment]
ah, Thanks for that info @nikhau

**Comment by nikhau** [comment]
Regarding the SDKv2 https://github.com/smokku/pebble/issues/83

**Comment by smokku** [comment]
You do not need applications support to upgrade firmware.
These are two different things.
I was able to bring-up my Pebble Time from recovery firmware to full firmware with no issue. https://plus.google.com/+TomaszSternaSMK/posts/Fn99JSPCnF6

**Comment by nikhau** [comment]
While digging for info regarding my Bluetooth pairing problems, I found this 
https://www.reddit.com/r/pebble/wiki/faq#wiki_q.3A_why_doesn.27t_pebble_use_bluetooth_4.0_le_on_android.3F
"One Bluetooth 4.0 LE connection used solely for receiving notifications via ANCS. The other is a Bluetooth "classic" connection, used for phone call notifications, communication with third party apps/faces, firmware updates, and pushing apps and faces to the watch."
I know it is for iOS + original Pebble.
However, at the same time the original Pebble don't use BLE when connected to Androids.

Now, with Pebble Time (Steel) it requires Android 4.3+, which have support for BLE. And also in Android phones, you are now supposed to have two pairings between phone and watch, i.e. both BLE and "classic" Bluetooth.

We all know that our Jollas don't support BLE very well ... 

I recieve phone notifications, but not sms/email notifications on my PTS when connected to Jolla.

Could this missing notifications be depending on missing BLE link?
If so, could the notifications (and other) be forced to use the "classic" BT link?

**Comment by Astaoth** [comment]
Maybe I have some reading problems but ... with the latest version where is the update button ????

**Comment by RobertMe** [comment]
Offtopic:
If you have a Time Steel you probably don't get firmware updates because the Time Steel isn't recognized. I have done some changes which will add support for the Time Steel (although firmware update support is untested, as you'll need to donate for it)

Ontopic:
I have also made some changes to show notifications in the timeline. HtheB has tested some iterations of this code (as I don't have my Time Steel yet). Currently there is only one issue left, which I just (hopefully) fixed, if HtheB has validated this fix I will create a pull request for these changes.
