### ISSUE TITLE
"SDKv2 isn't supported" on brand new Pebble Time Steel.

### ISSUE THREAD

**Issue by nikhau** [smokku/pebble#83]
Received my Pebble Time Steel, bluetooth pairing and then in the Pebble app I received this:

SDKv2 isn't supported.

Couldn't pretty much do anything either in phone nor in watch.
Had to connect the watch to an Android phone, to update firmware and get the watch running.

Pebble FW 3.something
Sailfish 1.1.9.28
Pebbled 1.3-1

**Comment by raketti** [comment]
My other half just got a brand new Time Round and has the error:
*"Your firmware is too old to support SDKv2 applications."*

Pebble App gives the following information:
Recovery: v3.2-prf5
Running: unknown
Latest: unknown

She can't even pair the Pebble with the app, so now it's basically useless if she doesn't find an Android or iOS App version of the Pebble App and update the firmware.

**Comment by smokku** [comment]
I do not have access to Pebble Time Round to even tackle this problem. :-(

**Comment by raketti** [comment]
Solved the issue by pairing and updating the Pebble with another phone.
