### ISSUE TITLE
Problems with pairing with a Pebble Time (Steel)

### ISSUE THREAD

**Issue by nikhau** [smokku/pebble#84]
This might rather be an issue with Pebble Time FW, but I will still raise it here to find out if anybody else is having similar problem.

I can pair my Jolla with my Pebble Time Steel. BUT everytime I get out of range (or toggle flight mode in the watch), I have to re-pair the devices in order to re-establish connection.
In the watch settings my Jolla is not stored as a paired device, not even after a succesful pairing, thus never being listed as paired.
In the Jolla, the watch is listed, and set to always allowed.
My Android phone, however gets saved in the list in the watch and has no problems to reconnect after out-of-range.

On a side note, in my Android phone, I have two pairings with my Pebble Time, one "regular" Bluetooth and then also a LE Bluetooth connection. Whereas the Jolla only have one pairing.

Pebble FW 3.4
Sailfish 1.1.9.28
Pebbled 1.3-1

**Comment by nikhau** [comment]
Just tried to connect an original Pebble (FW 2.9.1) to my Jolla, worked like a charm.
So there is something in my PTS that is not working properly.

**Comment by raketti** [comment]
It seems that the Pebble Time uses BT (4.0) LE, which if I recall correctly isn't supported in Jolla, thus not connecting correctly.

From the pebble support site (http://help.getpebble.com/customer/portal/articles/1959920-introduction-to-pebble-time?b_id=8309#Works):
> Pebble Time connects by Bluetooth LE (4.0) to your iPhone or Android device.

**Comment by nikhau** [comment]
@raketti thanks for your input.

Not sure that was the problem here. Pebble Time uses both "classic" Bluetooth and BLE.
Some of the notifications are appearently forced (by Apple policies) to be transmitted over BLE, while other stuff such firmware updates are transmitted over "classic" BT.

**Comment by nikhau** [comment]
I got it to finally work! 
After factory reset, a number of deleting pairings, re-pairing, I eventually got the pairing to get stuck in both the phone and watch.
Don't know why nor how, but somehow it managed to get into working order.

**Comment by raketti** [comment]
So a glitch in the Matrix then, glad to hear it works, been thinking of getting one myself.

**Comment by borishoeft** [comment]
Just got the same problem now for a week and I am not able to solve this.
Always after loosing contact I have to pair my Jolla phone withe my pebble time.
Factory reset of the watch and 1000 times pairing and unpairing didn't help.
