### ISSUE TITLE
Cannot install on Sailfish OS 2

### ISSUE THREAD

**Issue by BjoernRuberg** [smokku/pebble#86]
Installing on Sailfish OS 1.1.9.28 fails because of a missing package qt5-qtconnectivity-qtbluetooth
I think Sailfish has switched to bluez  - so this app might need adjustments?

**Comment by smokku** [comment]
This report contradicts #87 which reports a bug on a version working on 1.1.9.28

**Comment by BjoernRuberg** [comment]
Would be great if there is a way to install. That is the console output when trying to do it. It's in German but I think the problem with the missing package is obvious.

> [root@Jolla nemo]# pkcon install pebble
> Installieren 
> [...]
> Pakete werden installiert                                                                                                              
> [===================================================================]        
>Die folgenden Pakete müssen installiert werden:
> qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.3.60.armv7hl       QtBluetooth
> pebble-1.4-1.armv7hl   Support for Pebble watch in SailfishOS
> Mit Änderungen fortfahren? [N/y] y
> [...]                                                                                   >                                                                                                                                             
> Schwerwiegender Fehler: Datei './qt/armv7hl/qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.3.60.armv7hl.rpm' > nicht auf dem Medium 'https://releases.jolla.com/releases/1.1.9.28/jolla/armv7hl/' gefunden.

**Comment by BjoernRuberg** [comment]
Maybe it works when pebble is already installed when sailfish is upgraded. The old qtbluetooth package might simply remain in place then.

**Comment by abranson** [comment]
No, someone else had a dependency problem with that package some time ago. I haven't managed to find the issue yet, but it should be in here somewhere. I can't remember how he resolved it, but it seems that some phones have got themselves in a state where the qt-bluetooth package is broken.

**Comment by BjoernRuberg** [comment]
No, I think it is as I said. 
I manually fetched the package from the last Sailfish OS 1 release and installed the rpm on the phone.
After that pebble installed - it connected to the watch. Even got notifications so I think everything works now.

So the problem is that the package is is missing in the 1.1.9 repo for reasons I do not know.

**Comment by smokku** [comment]
I think this issue should be reported on http://together.jolla.com/questions/ then...

**Comment by d0b3rm4n** [comment]
Just verified, the package is not removed. You can't browse the folder, but the file is there:

https://releases.jolla.com/releases/1.1.9.28/jolla/armv7hl/qt/armv7hl/qt5-qtconnectivity-qtbluetooth-5.2.0+git0-1.3.61.armv7hl.rpm

update the repo data with:
    pkcon refresh force

**Comment by BjoernRuberg** [comment]
Confirmed. After "pkcon refresh force" I was able to fetch the package from the repo.

**Comment by smokku** [comment]
closing then
